name: Status tracking

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Install Dependencies
      run: pip install pyyaml requests python-telegram-bot asyncio

    - name: Run Tracker Script
      run: python3 scripts/tracker.py

    - name: Run Page Updater Script
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: python3 scripts/issues.py

    - name: Update Changes (If any)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        changed=$(git diff --numstat --cached | wc -l)
        if [[ "$changed" -eq 0 ]]; then
        echo "State of status remains same as of previous check. Exiting"
        exit 0
        fi
        git commit -m "Sync: $(date)"
        git push